### PR TITLE
A few tiny things

### PR DESCRIPTION
**Pull request by marineb**

### CODE REVIEW

**Comment by HeahDude** [comment]
Conflicts with #1242. Could we please merge this one first, I need to remove the"desintox" there too.

**Comment by tgalopin** [comment]
We will merge https://github.com/EnMarche/en-marche.fr/pull/1242 first, yes.

**Comment by tgalopin** [comment]
@marineb now https://github.com/EnMarche/en-marche.fr/pull/1242 is merged, can you rebase this? Thanks :) !

**Comment by HeahDude** [comment]
Rebased and updated.

**Pull request merged**
