### PR TITLE
Inject UrlGenerator instead of Router

### PR DESCRIPTION
**Pull request by Remg**

### CODE REVIEW

**Comment by tony-tran** [comment]
Good catches !

**Comment by Remg** [comment]
image-aladdin-1

**Comment by thomasbisignani** [comment]
:medal_sports:

**Comment by tony-tran** [comment]
Can you change https://github.com/EnMarche/en-marche.fr/blob/master/src/Redirection/Dynamic/RedirectToRemoveUuidHandler.php#L15 please ? 

use `UrlMatcherInterface`

**Comment by tony-tran** [comment]
Thank you for contribution @Remg

**Comment by thomasbisignani** [comment]
Congrats @Remg. You've been awarded the "Constructor injection" badge on SymfonyConnect.

**Pull request merged**
