### PR TITLE
Don't depend on container

### PR DESCRIPTION
**Pull request by mleko**

### CODE REVIEW

**Comment by tgalopin** [comment]
There is a circular reference as you are loading redis, which is loading the logger, which is booting the app, which is loading redis. That's the reason why I used the container directly. If you find something to fix this, I'll be ok with merging this PR.

**Comment by HeahDude** [comment]
Let's wait for the upcoming Symfony 3.3 service locators then.

**Comment by mleko** [comment]
Simple solutions are the best ones, use lazy service

**Comment by HeahDude** [comment]
Hello @mleko! Thank you for this contribution, with the recent release of Symfony 3.3, I propose to fix this in #1179 so I'm closing here.

I hope we will see other PRs from you, cheers!

**Pull request closed without merging**
